### PR TITLE
Gravatar as known_devices picture

### PR DESCRIPTION
**Pull request by robbiet480**
See also home-assistant/home-assistant#2836.

Thanks to @ngrhd for suggesting it on the [forums](https://community.home-assistant.io/t/pull-avatars-from-gravatars-for-known-devices/3009). I was already using Gravatar but had the URLs hardcoded.

### CODE REVIEW

**Comment by Landrash** [comment]
That's really cool! Good idea.

**Comment by robbiet480** [comment]
@Landrash Bit harder to do since Facebook's API now requires authentication for all calls.

**Comment by Landrash** [comment]
@robbiet480 Wasn't aware of that. I'll have to get my significant other a gravatar account then. Cool feature and thanks for adding it.

**Comment by balloob** [comment]
The documentation update should have an example of how to add a gravatar picture.

**Comment by robbiet480** [comment]
Got it

**Comment by robbiet480** [comment]
🐬

**Pull request merged**
