### PR TITLE
Add Vagrant installation docs

### PR DESCRIPTION
**Pull request by shaftoe**
Full credits to @spuder who's started the whole Vagrant idea and first version of this document

### CODE REVIEW

**Comment by spuder** [comment]
Need to clarify that the user first needs to cd to home-assistant/virtualization/vagrant

**Comment by shaftoe** [comment]
@spuder can you elaborate on that? The user is reminded to cd into the right folder in every code snippet, at lines 39, 50, 63, 72 and 81. Do you mean perhaps we should clarify why is needed?

**Comment by spuder** [comment]
The instructions assume that the user is cloning into their home directory. 

Maybe instead of using an absolute path, the instructions should use relative paths? 

```
git clone https://github.com/home-assistant/home-assistant.git
cd ~/home-assistant/virtualization/vagrant
```

```
git clone https://github.com/home-assistant/home-assistant.git
cd ./home-assistant/virtualization/vagrant
```

**Comment by shaftoe** [comment]
@spuder got it. Yeah why not, the clearer the better. I also try to put in some note before the snippets to explain a bit why is needed

**Pull request merged**
