### PR TITLE
Sprinkler example

### PR DESCRIPTION
**Pull request by Teagan42**
Add a weather aware sprinkler system example on the raspberry pi

### CODE REVIEW

**Comment by balloob** [comment]
Can you point your PR at `master` branch?

**Comment by balloob** [comment]
Although, you probably have to rebase because we don't want to merge the current next branch into master yet.

**Comment by Landrash** [comment]
@Teagan42 You should probaly make a Readme file in the repository with a short explanation and maybee a screenshot. Would make it more user friendly for the random person googling the subject.

**Comment by Teagan42** [comment]
No one likes your logic @Landrash ! - Yeah I already got a few people asking me for that.

@balloob I can rebase and do it off master this weekend. Busy today.

**Pull request closed without merging**
