### PR TITLE
New cookbook info for setting up Tor

### PR DESCRIPTION
**Pull request by n8fr8**
This is an example about how you can configure Tor to provide secure remote access to your home assitance instance as an Onion site, through Tor’s Hidden Service feature. With this enabled, you do not need to open your firewall ports or setup HTTPS to enable secure remote access.

### CODE REVIEW

**Comment by balloob** [comment]
Awesome! 🐬

**Comment by balloob** [comment]
Could you point this at the `master` branch? No need to not publish this article till the next release.

**Comment by n8fr8** [comment]
Oh sorry got confused at the branch naming conventions

**Comment by n8fr8** [comment]
Resubmitted here: https://github.com/home-assistant/home-assistant.io/pull/627

**Pull request closed without merging**
