### PR TITLE
Added examples and helpful info to HDMI-CEC component page

### PR DESCRIPTION
**Pull request by andrew-curtis**
Hi guys,

I've never created a pull request or contributed code before so apologies if I am breaking any conventions. This is my first time. (be gentle. 😄 )

I have just added some information that I would have found very helpful if it was there to begin with.

What are your thoughts on my additions?

Cheers,
AC

### CODE REVIEW

**Comment by kellerza** [comment]
Welcome :smile:

Did you do this patch through the web or through `git` cmdline?

If git you might have to rebase on the current `next` with `git pull --rebase upstream next` and then push again

If this is for current functionality, you should create the PR against `master` instead of the `next` branch (its probably whats going on here)

**Comment by fabaff** [comment]
This looks like it could be made against `master`.

**Comment by andrew-curtis** [comment]
Hi guys,

Thanks for the feedback.

I did this through the web.So other than creating it against the wrong branch, you're happy with my contributions?

I will do my best to change it to master now.

**Comment by andrew-curtis** [comment]
submitted to wrong branch

**Pull request closed without merging**
